# Generated by Django 3.0.8 on 2020-08-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('necessity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NecessityCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='necessity',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='necessity',
            name='option',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
