# Generated by Django 3.0.8 on 2020-08-09 03:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('necessity', '0002_auto_20200806_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='necessity',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='necessity',
            name='option',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='necessityuser',
            unique_together={('user', 'necessity')},
        ),
    ]
