# Generated by Django 3.0.7 on 2020-08-10 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('necessity', '0003_auto_20200809_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='NecessityUserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_category', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('CHANGE', 'Change')], default='CHANGE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('necessity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='necessity.Necessity')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
