# Generated by Django 3.0.7 on 2020-08-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('necessity', '0004_necessityuserlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='necessityuser',
            name='used',
            field=models.BooleanField(default=True),
        ),
    ]
