# Generated by Django 3.0.7 on 2020-10-11 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20201011_1229'),
        ('necessity', '0007_delete_necessitycounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='NecessityHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('price', models.PositiveIntegerField(null=True)),
                ('count', models.PositiveIntegerField(db_index=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='necessity_houses', to='accounts.House')),
                ('necessity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='necessity_houses', to='necessity.Necessity')),
            ],
            options={
                'unique_together': {('house', 'necessity')},
            },
        ),
        migrations.CreateModel(
            name='NecessityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'create'), ('UPDATE', 'update'), ('DELETE', 'delete'), ('COUNT', 'count')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('necessity_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='necessity_logs', to='necessity.NecessityHouse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='necessity_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='necessityuserlog',
            name='necessity',
        ),
        migrations.RemoveField(
            model_name='necessityuserlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='NecessityUser',
        ),
        migrations.DeleteModel(
            name='NecessityUserLog',
        ),
    ]
