export const userStatus = {
  NONE: 'NONE',
  WAITING: 'WAITING',
  SUCCESS: 'SUCCESS',
  FAILURE: 'FAILURE',
  FAILURE_AUTHENTICATION: 'FAILURE_AUTHENTICATION',
  FAILURE_INACTIVE: 'FAILURE_INACTIVE',
  FAILURE_INFO: 'FAILURE_INFO',
  FAILURE_USERNAME: 'FAILURE_USERNAME',
  FAILURE_EMAIL: 'FAILURE_EMAIL',
};

export const necessityStatus = {
  NONE: 'NONE',
  WAITING: 'WAITING',
  SUCCESS: 'SUCCESS',
  FAILURE: 'FAILURE',
  FAILURE_NAME: 'FAILURE_NAME',
  FAILURE_LEADER: 'FAILURE_LEADER',
  FAILURE_MEMBER: 'FAILURE_MEMBER',
  FAILURE_NOT_FOUND: 'FAILURE_NOT_FOUND',
};

export const necessityUserLogStatus = {
  NONE: 'NONE',
  SUCCESS: 'SUCCESS',
  FAILURE: 'FAILURE',
};

export const houseStatus = {
  NONE: 'NONE',
  WAITING: 'WAITING',
  SUCCESS: 'SUCCESS',
  FAILURE: 'FAILURE',
  FAILURE_AUTHENTICATION: 'FAILURE_AUTHENTICATION',
  FAILURE_EMAIL: 'FAILURE_EMAIL',
  FAILURE_INACTIVE: 'FAILURE_INACTIVE',
  FAILURE_INVITE_LEADER: 'FAILURE_INVITE_LEADER',
  FAILURE_LEAVE_LEADER: 'FAILURE_LEAVE_LEADER',
  FAILURE_TOSS_LEADER: 'FAILURE_TOSS_LEADER',
  FAILURE_TOSS_ME: 'FAILURE_TOSS_ME',
  FAILURE_USERNAME: 'FAILURE_USERNAME',
  FAILURE_REMOVE_MEMBER: 'FAILURE_REMOVE_MEMBER',
  FAILURE_REMOVE_LEADER: 'FAILURE_REMOVE_LEADER',
};
