export const userStatus = {
  NONE: 'NONE',
  WAITING: 'WAITING',
  SUCCESS: 'SUCCESS',
  FAILURE: 'FAILURE',
  FAILURE_AUTHENTICATION: 'FAILURE_AUTHENTICATION',
  FAILURE_INACTIVE: 'FAILURE_INACTIVE',
  FAILURE_INFO: 'FAILURE_INFO',
  FAILURE_USERNAME: 'FAILURE_USERNAME',
  FAILURE_EMAIL: 'FAILURE_EMAIL',
};

export const necessityStatus = {
  NONE: 'NONE',
  WAITING: 'WAITING',
  SUCCESS: 'SUCCESS',
  FAILURE: 'FAILURE',
  FAILURE_NAME: 'FAILURE_NAME',
};

export const necessityUserLogStatus = {
  NONE: 'NONE',
  SUCCESS: 'SUCCESS',
  FAILURE: 'FAILURE',
};
