export const userStatus = {
  NONE: 'NONE',
  WAITING: 'WAITING',
  SUCCESS: 'SUCCESS',
  FAILURE: 'FAILURE',
  FAILURE_USERNAME: 'FAILURE_USERNAME',
};

export const necessityStatus = {
  NONE: 'NONE',
  WAITING: 'WAITING',
  SUCCESS: 'SUCCESS',
  FAILURE: 'FAILURE',
  FAILURE_NAME: 'FAILURE_NAME',
};
