version: "3.3"
services:
  nongjang:
    container_name: code
    restart: always
    environment:
      - MODE=prod
    build:
      context: ./nongjang/
      dockerfile: Dockerfile

  nginx:
    container_name: nginx
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - nongjang
