FROM nginx:1.19.0

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx-app.conf /etc/nginx/conf.d/default.conf
COPY nongjang/uwsgi_params /etc/nginx/uwsgi_params

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
